version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/var/www
        ports:
            - "8000:80"
        networks:
            - app-network
        depends_on:
            - db
            - redis

    cms:
        image: strapi/strapi
        environment:
            DATABASE_CLIENT: postgres
            DATABASE_HOST: db
            DATABASE_PORT: 5432
            DATABASE_NAME: app
            DATABASE_USERNAME: user
            DATABASE_PASSWORD: password
        volumes:
            - ./cms:/srv/app
        ports:
            - "1337:1337"
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: postgres:13
        container_name: db-1
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        networks:
            - app-network

    redis:
        image: redis:latest
        networks:
            - app-network

networks:
    app-network:
        driver: bridge